import{a as P,S as B,i}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const n of a.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(e){if(e.ep)return;e.ep=!0;const a=s(e);fetch(e.href,a)}})();const M="52595115-c90df6dee3e8dfc0035bbe5c3",R="https://pixabay.com/api/",u=15;async function y(r,t=1){const{data:s}=await P.get(R,{params:{key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:u,page:t}});return s}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),m=document.querySelector(".load-more"),$=new B(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const t=r.map(({largeImageURL:s,webformatURL:l,tags:e,likes:a,views:n,comments:q,downloads:E})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${l}" alt="${e}" loading="lazy" />
        </a>
        <div class="gallery-info">
          <div class="gallery-stats"><span class="gallery-stat-label">Likes</span><span class="gallery-stat-value">${a}</span></div>
          <div class="gallery-stats"><span class="gallery-stat-label">Views</span><span class="gallery-stat-value">${n}</span></div>
          <div class="gallery-stats"><span class="gallery-stat-label">Comments</span><span class="gallery-stat-value">${q}</span></div>
          <div class="gallery-stats"><span class="gallery-stat-label">Downloads</span><span class="gallery-stat-value">${E}</span></div>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function O(){f.innerHTML=""}function v(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}function w(){m.classList.remove("hidden")}function b(){m.classList.add("hidden")}const S=document.querySelector(".form"),g=S.querySelector("input[name='search']"),A=document.querySelector(".load-more");let d="",o=1,c=0;S.addEventListener("submit",_);A.addEventListener("click",x);async function _(r){r.preventDefault();const t=g.value.trim();if(!t){i.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}d=t,o=1,c=0,O(),b(),v();try{const s=await y(d,o);if(!s.hits.length){i.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}c=s.totalHits,h(s.hits),o*u<c&&w(),g.value=""}catch{i.error({title:"Error",message:"Something went wrong while fetching images.",position:"topRight"})}finally{L()}}async function x(){o+=1,b(),v();try{const r=await y(d,o);h(r.hits);const t=document.querySelector(".gallery .gallery-item");if(t){const{height:s}=t.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}o*u<c?w():i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({title:"Error",message:"Something went wrong while fetching images.",position:"topRight"})}finally{L()}}
//# sourceMappingURL=index.js.map
